# hidden yaml configuration to only run pipelines when according source directory has been modified
.compiler-rules: &compiler-changes
  only:
    changes:
      - compiler/**/*

.darkmode-rules: &darkmode-changes
  only:
    changes:
      - dark-mode/**/*

.project-rules: &project-changes
  only:
    changes:
      - project/**/*

.gateway-rules: &gateway-changes
  only:
    changes:
      - gateway/**/*

.ui-rules: &ui-changes
  only:
    changes:
      - ui/**/*

.discovery-rules: &discovery-changes
  only:
    changes:
      - discoveryserver/**/*
stages:
  - build
  - test
  - package
  - publish
  - deploy

# login to private docker registry
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# building all services as docker images
compiler-publish:
  stage: publish
  script:
    - cd $IMAGE_DIR
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/compiler-service
    IMAGE_DIR: compiler
  <<: *compiler-changes

darkmode-publish:
  stage: publish
  script:
    - cd $IMAGE_DIR
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/darkmode-service
    IMAGE_DIR: dark-mode
  <<: *darkmode-changes

project-publish:
  stage: publish
  script:
    - cd $IMAGE_DIR
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/project-service
    IMAGE_DIR: project
  <<: *project-changes

gateway-publish:
  stage: publish
  script:
    - cd $IMAGE_DIR
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/gateway-service
    IMAGE_DIR: gateway
  <<: *gateway-changes

ui-publish:
  stage: publish
  script:
    - cd $IMAGE_DIR
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ui-service
    IMAGE_DIR: ui
  <<: *ui-changes

discovery-publish:
  stage: publish
  script:
    - cd $IMAGE_DIR
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/discovery-service
    IMAGE_DIR: discoveryserver
  <<: *discovery-changes

compiler-build:
  stage: build
  script:
    - cd compiler
    - mvn clean compile
  artifacts:
    paths:
      - compiler/target/*
  <<: *compiler-changes

darkmode-build:
  stage: build
  script:
    - cd dark-mode
    - mvn clean compile
  artifacts:
    paths:
      - dark-mode/target/*
  <<: *darkmode-changes

project-build:
  stage: build
  script:
    - cd project
    - mvn clean compile
  artifacts:
    paths:
      - project/target/*
  <<: *project-changes

gateway-build:
  stage: build
  script:
    - cd gateway
    - mvn clean compile
  artifacts:
    paths:
      - gateway/target/*
  <<: *gateway-changes

ui-build:
  stage: build
  script:
    - cd ui
    - mvn clean compile
  artifacts:
    paths:
      - ui/target/*
  <<: *ui-changes

discovery-build:
  stage: build
  script:
    - cd discoveryserver
    - mvn clean compile
  artifacts:
    paths:
      - discoveryserver/target/*
  <<: *discovery-changes

compiler-test:
  stage: test
  script:
    - cd compiler
    - mvn test
  <<: *compiler-changes

compiler-package:
  stage: package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
  script:
    - cd compiler
    - mvn package
  artifacts:
    paths:
      - compiler/target/*.jar
  <<: *compiler-changes

darkmode-package:
  stage: package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
  script:
    - cd dark-mode
    - mvn package
  artifacts:
    paths:
      - dark-mode/target/*.jar
  <<: *darkmode-changes

project-package:
  stage: package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
  script:
    - cd project
    - mvn package
  artifacts:
    paths:
      - project/target/*.jar
  <<: *project-changes

gateway-package:
  stage: package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
  script:
    - cd gateway
    - mvn package
  artifacts:
    paths:
      - gateway/target/*.jar
  <<: *gateway-changes

ui-package:
  stage: package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
  script:
    - cd ui
    - mvn package
  artifacts:
    paths:
      - ui/target/*.jar
  <<: *ui-changes

discovery-package:
  stage: package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
  script:
    - cd discoveryserver
    - mvn package
  artifacts:
    paths:
      - discoveryserver/target/*.jar
  <<: *discovery-changes

deploy:
  stage: deploy
  script:
    - touch $ENV_VARS
    - echo EUREKA_SERVER=$EUREKA_SERVER >> $ENV_VARS
    - echo EUREKA_PORT=$EUREKA_PORT >> $ENV_VARS
    - echo POSTGRES_DB=$POSTGRES_DB >> $ENV_VARS
    - echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> $ENV_VARS
    - echo POSTGRES_USER=$POSTGRES_USER >> $ENV_VARS
    - touch $KEY_FILE && echo $SSH_PRIV_KEY | base64 -d > $KEY_FILE
    - chmod 400 $KEY_FILE
    - scp -o "StrictHostKeyChecking=no" -i $KEY_FILE $ENV_VARS $SSH_HOST:~/
    - scp -o "StrictHostKeyChecking=no" -i $KEY_FILE docker-compose.prod.yml $SSH_HOST:~/docker-compose.yaml
    - ssh -o "StrictHostKeyChecking=no" -i $KEY_FILE $SSH_HOST "sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -o "StrictHostKeyChecking=no" -i $KEY_FILE $SSH_HOST "source $ENV_VARS && sudo docker-compose pull && sudo docker-compose up --force-recreate -d"
  variables:
    SSH_HOST: raph.hohmann@34.107.85.135
    KEY_FILE: ase_practical.privkey
    ENV_VARS: .env
    # TODO: Remove
    #  only:
    #    refs:
    #      - master
