before_script:
    - ls
    - docker build -t mvn-gcc:latest .

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - cd compiler
    - docker run --rm mvn-gcc mvn clean compile
    - cd ..
    - cd dark-mode
    - mvn clean compile
    - cd ..
    - cd project
    - mvn clean compile
    - cd ..

test:
  stage: test
  script:
    - cd compiler
    - mvn test
    - cd ..
    - cd dark-mode
    - mvn test
    - cd ..
    - cd project
    - mvn test
    - cd ..

package:
  stage: package
  script: mvn package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
