stages:
  - build
  - test
  - package

# building all services as docker containers
before_script:
    - docker build -t compiler-service ./compiler/
    - docker build -t darkmode-service ./dark-mode/
    - docker build -t project-service ./project/

build:
  stage: build
  script:
    - docker run --rm compiler-service mvn clean compile
    - docker run --rm darkmode-service mvn clean compile
    - docker run --rm project-service mvn clean compile

test:
  stage: test
  script:
    - docker run --rm compiler-service mvn test
    - docker run --rm darkmode-service mvn test
    - docker run --rm project-service mvn test

package:
  stage: package
  script: mvn package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
