.project-rules: &project-changes
  only:
    changes:
      - project/**/*

stages:
  - build
  - package
  - publish

# login to private docker registry
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

project-publish:
  stage: publish
  script:
    - cd $IMAGE_DIR
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/project-service
    IMAGE_DIR: project
  <<: *project-changes

project-build:
  stage: build
  script:
    - cd project
    - mvn clean compile
  artifacts:
    paths:
      - project/target/*
  <<: *project-changes

project-package:
  stage: package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
  script:
    - cd project
    - mvn package
  artifacts:
    paths:
      - project/target/*.jar
  <<: *project-changes
