stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - docker build -t compiler-service -f compiler
    - docker run --rm compiler-service mvn clean compile

test:
  stage: test
  script:
    - cd compiler
    - mvn test
    - cd ..
    - cd dark-mode
    - mvn test
    - cd ..
    - cd project
    - mvn test
    - cd ..

package:
  stage: package
  script: mvn package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
