stages:
  - imaging
  - build
  - test
  - package

# building all services as docker containers
before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull
    - docker build -t compiler-service ./compiler/
    - docker build -t darkmode-service ./dark-mode/
    - docker build -t project-service ./project/

image-compiler-service:
  stage: imaging
  script:
    - docker build -t $CI_REGISTRY/ase20-group1-2/OnlineIDE/compiler-service:latest ./compiler/

build:
  stage: build
  script:
    - docker run --rm compiler-service mvn clean compile
    - docker run --rm darkmode-service mvn clean compile
    - docker run --rm project-service mvn clean compile

test:
  stage: test
  script:
    - docker run --rm compiler-service mvn test
    - docker run --rm darkmode-service mvn test
    - docker run --rm project-service mvn test

package:
  stage: package
  script: mvn package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
