stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - docker build -t compiler-service ./compiler/
    - docker run --rm compiler-service mvn clean compile
    - docker build -t darkmode-service ./dark-mode/
    - docker run --rm darkmode-service mvn clean compile
    - docker build -t project-service ./project/
    - docker run --rm project-service mvn clean compile

test:
  stage: test
  script:
    - cd compiler
    - mvn test
    - cd ..
    - cd dark-mode
    - mvn test
    - cd ..
    - cd project
    - mvn test
    - cd ..

package:
  stage: package
  script: mvn package
  variables:
    MAVEN_OPTS: "-DskipTests=true"
