version: "3.8"

networks:
  online-ide:
    driver: bridge
  online-ide-database:
    driver: bridge

volumes:
  projectsdata:

services:
  discovery:
    image: gitlab.lrz.de:5005/ase20-group1-2/ase20-practical-exercise/discovery-service:latest
    restart: on-failure
    networks:
      - online-ide
    environment:
      - EUREKA_PORT=${EUREKA_PORT}
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"

  gateway:
    image: gitlab.lrz.de:5005/ase20-group1-2/ase20-practical-exercise/gateway-service:latest
    restart: on-failure
    environment:
      - EUREKA
    networks:
      - online-ide
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}
    ports:
      - "8000:8000"

  compiler:
    image: gitlab.lrz.de:5005/ase20-group1-2/ase20-practical-exercise/compiler-service:latest
    restart: on-failure
    networks:
      - online-ide
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}

  darkmode:
    image: gitlab.lrz.de:5005/ase20-group1-2/ase20-practical-exercise/darkmode-service:latest
    restart: on-failure
    networks:
      - online-ide
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}
    ports:
      - "8083:8083"

  ui:
    image: gitlab.lrz.de:5005/ase20-group1-2/ase20-practical-exercise/ui-service:latest
    restart: on-failure
    networks:
      - online-ide
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}

  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - "projectsdata:/var/lib/postgresql/data"
    restart: on-failure
    networks:
      - online-ide-database

  project:
    image: gitlab.lrz.de:5005/ase20-group1-2/ase20-practical-exercise/project-service:latest
    restart: on-failure
    networks:
      - online-ide
      - online-ide-database
    environment:
      - POSTGRES_URL=postgresdb   # must be same name as postgresdb-service
      - POSTGRES_PORT=5432        # use default postgres port
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
