spring:
  application:
    name: gateway-service
#security:
#  oauth2:
#    client:
#      clientId: f5adcf1af55584411d38fe146dccafd6e791771a8e8e18739d229f2d789a9a2a
#      clientSecret: e0b58ba7e75b808991e550dd0bf6e11402b0551eb75cba19a2677996045fc10e
#      accessTokenUri: https://gitlab.lrz.de/oauth/token
#      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
#      scope:
#        - read_user
#        - api
#    resource:
#      userInfoUri: https://gitlab.lrz.de/api/v4/user
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
server:
  port: ${PORT:8000}
zuul.host.socket-timeout-millis: 20000
zuul.host.connect-timeout-millis: 20000
zuul:
  ignoredServices: '*'
  ignoredPatterns:
    - /user
    - /login
    - /logout
    - /authenticated
  routes:
    project-service:
      path: /api/project/**
      stripPrefix: false
      # sensitiveHeaders: Cookie,Set-Cookie # Authentication
    compiler-service:
      path: /api/compile/**
      stripPrefix: false
    darkmode-service:
      path: /api/dark-mode/**
      stripPrefix: false
    ui-service:
      path: /**
ribbon.ConnectTimeout: 10000
ribbon.ReadTimeout: 10000
# proxy:
 # auth:
   # routes:
     # project-service: oauth2
