spring:
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
server:
  port: ${PORT:8000}
zuul.host.socket-timeout-millis: 20000
zuul.host.connect-timeout-millis: 20000
zuul:
  ignoredServices: '*'
  routes:
    project-service:
      path: /project/**
    compiler-service:
      path: /compile/**
      stripPrefix: false
    darkmode-service:
      path: /darkmode/**
      stripPrefix: false
    ui-service:
      path: /**
ribbon.ConnectTimeout: 10000
ribbon.ReadTimeout: 10000
